# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('validtill', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promos.Promo')),
            ],
        ),
    ]
