# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promo',
            name='title',
            field=models.CharField(default='Promo title', max_length=50),
            preserve_default=False,
        ),
    ]
